version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
    - './init_db.sql:/docker-entrypoint-initdb.d/init_db.sql'
    - './data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: "${DATABASE_NAME}"
    ports:
      - '5432:5432'